### ISSUE TITLE
Every Browserconnection is new to dongle

### ISSUE THREAD

**Issue by R03LTjuh** [donothingloop/rtl_heatmap#1]
I dont realy mind this issue its your desission offcource
i am warmly known a webserver can handle large connections,
but than from every browser a new connection to the dongle
how does it handle if we users use this for large connection interface.

shouldn't it be better to just allow one connection to stream it to the webserver instead of every browser a newone.
Or meybe better choose between these both options.

My deepest respect
Roel Adema

**Comment by donothingloop** [comment]
I think that you do not quite understand how the streaming function works.

It uses a websocket connection on which new data is pushed from the server to all connected clients simultaneously. But there is only one "connection" to the dongle which is handled by rtl_power.
The python server only reads the output from rtl_power on stdin and pushes it over the websocket connection to the connected clients.

But if you mean that your sdr system is underpowered for a large number of client connections and if you want to use for instance a Raspberry PI which does not quite offer the needed processing power, you could pipe the output of rtl_power through netcat and receive them with another netcat command on a webserver and then pipe them to the rtl_heatmap server.

This could be done like this:

1. Run this on your **webserver**:
```bash
netcat -l -p 7000 | python rtl_heatmap_server.py
```

2. Run this on your **Raspberry PI**:

You have to replace the following things:
|Placeholder|New Value|
|-|-|
|<START_FREQ>|Starting frequency of the scan|
|<STOP_FREQ>|Maximal frequency|
|<SERVER_IP>|The ip of your webserver|

```bash
rtl_power -f <START_FREQ>:<STOP_FREQ>:0.3k -g 35 -i 1 - |  netcat <SERVER_IP> 7000
```
