### ISSUE TITLE
rtl_heatmap_server streaming error

### ISSUE THREAD

**Issue by davidcomtois** [donothingloop/rtl_heatmap#2]
a few dozen sending messages then...
sending message to  ('127.0.0.1', 41293)
Traceback (most recent call last):
  File "rtl_heatmap_server.py", line 52, in <module>
    triggerEvent(json.dumps(lst))
  File "rtl_heatmap_server.py", line 34, in triggerEvent
    client.sendEvent(evt)
  File "rtl_heatmap_server.py", line 30, in sendEvent
    self.sendMessage(evt)
  File "C:\xampp\htdocs\rtl_heatmap-master\server\SimpleWebSocketServer.py", lin
e 315, in sendMessage
    self.sendBuffer(header + s)
  File "C:\xampp\htdocs\rtl_heatmap-master\server\SimpleWebSocketServer.py", lin
e 281, in sendBuffer
    raise e
socket.error: [Errno 10035] A non-blocking socket operation could not be complet
ed immediately

**Comment by donothingloop** [comment]
Sorry, I'm currently trying to reproduce this one, but have not yet succeeded. 
Could you tell me a bit more about your setup?
Are you streaming over the internet?
Which browser do you use?

Thanks

**Comment by davidcomtois** [comment]
Localhost as indicated in the error message. On my end, I added a 'try' block around the send message function (with an error message printed to screen, to inform the user it failed to send a message). Having the try block also allows it to recover and continue trying to send messages rather then fatally stopping. 

One additional thing I did was add a time prefix to the messages printing to the screen so you can see the progression of time in the command line server view. 

If you'd like any version numbers or other info, let me know.

**Comment by donothingloop** [comment]
What is currently missing is a mechanism which keeps a buffer of failed messages and retries to send them. Because this is not yet implemented I did not include a try-catch block around the sendMessage function, but it would be better if I included one and just printed an error message. Will do this.

But this does not quiet explain why your messages do not arrive at your browser. Your browser version would be great. :)

**Comment by davidcomtois** [comment]
Latest and greatest chrome, v44

**Comment by donothingloop** [comment]
Ok, I have to admit that I did not test this on windows.
I'll try if I can get it running on windows with chrome v44.

**Comment by donothingloop** [comment]
Btw. Do you get any errors on the chrome javascript console?
https://developer.chrome.com/devtools/docs/console

**Comment by davidcomtois** [comment]
No worries, not being a native python guy to suggest a fix myself, I'm
happy with the "failed to send message". Down the road you can nail down
resending options. If I can help anymore, let me know.
