### ISSUE TITLE
Can no longer display csv files from rtl_power

### ISSUE THREAD

**Issue by wgaylord** [donothingloop/rtl_heatmap#4]
For some reason the demo site (have not tried a local version) won't process any files from rtl_power, It just says "The image was empty or an unknown error occurred."

I am not sure if maybe rtl_power had some sort of update that broke this or what.

**Comment by Kahn** [comment]
Seems to be working for me locally @wgaylord

**Comment by donothingloop** [comment]
Hi, I migrated it yesterday to a new server, so it should load much faster now, but maybe something broke.

Could please check your settings, they may have got lost when the page was switched to https?
I'll take a more detailed look in a couple of hours.

**Comment by donothingloop** [comment]
Sorry, did miss that this is from november :/

**Comment by donothingloop** [comment]
Should work now on the demo version.
The version there was not the current one from this repo.
