### ISSUE TITLE
code EINTEGRITY error

### ISSUE THREAD

**Issue by Bleach665** [donothingloop/rtl_heatmap#5]
Windows 10, node.js v12.16.2.
I try to install rtl_heatmap:
`npm install -g bower`
and receive an error:
````
npm ERR! code EINTEGRITY
npm ERR! sha512-1SrJnXnkP9soITHptSO+ahx3QKp3cVzn8poI6ujqc5SeOkg5iqM1pK9H+DSc2OQ8SnO0jC/NG4Ur/UIwy7574A== integrity checksum failed when using sha512: wanted sha512-1SrJnXnkP9soITHptSO+ahx3QKp3cVzn8poI6ujqc5SeOkg5iqM1pK9H+DSc2OQ8SnO0jC/NG4Ur/UIwy7574A== but got sha512-nUbMTnP2XI3rEopZiCVhalMxma2aILcLF7FjxjShPvibHtVeG1AojDGLOLL5ssAlP2f7v0zJM2/ySMPlZav5mg==. (195922 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bleach\AppData\Roaming\npm-cache\_logs\2020-04-20T09_19_11_312Z-debug.log
````
[2020-04-20T09_19_11_312Z-debug.log](https://github.com/donothingloop/rtl_heatmap/files/4502442/2020-04-20T09_19_11_312Z-debug.log)

**Comment by donothingloop** [comment]
As bower seems to be no longer recommended and the install may be broken, I switched to npm in the latest commit 27a89c3.
Please use the new instructions from the README to install.
